// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections wi.0ll be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.commands.*;
import jdk.jfr.Threshold;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.NeutralMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX leftFrontMotor;
private WPI_TalonSRX leftBackMotor;
private WPI_TalonSRX rightFrontMotor;
private WPI_TalonSRX rightBackMotor;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private static final double TICKS_PER_FOOT;
    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
leftFrontMotor = new WPI_TalonSRX(2);
 
 

leftBackMotor = new WPI_TalonSRX(3);
 
 

rightFrontMotor = new WPI_TalonSRX(7);
 
 

rightBackMotor = new WPI_TalonSRX(8);
 
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        brake();
        //coast();
        
        rightFrontMotor.setInverted(true);
        
        rightBackMotor.setInverted(true);

        leftBackMotor.follow(leftFrontMotor);
      
        rightBackMotor.follow(rightFrontMotor);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
  
    public void run(double l, double r) {
        leftFrontMotor.set(l);
        rightFrontMotor.set(r);
        // test, test, test
    }

    public void brake(){
        leftFrontMotor.setNeutralMode(NeutralMode.Brake);
        leftBackMotor.setNeutralMode(NeutralMode.Brake);
        rightFrontMotor.setNeutralMode(NeutralMode.Brake);
        rightBackMotor.setNeutralMode(NeutralMode.Brake);
    }

    public void coast(){
        leftFrontMotor.setNeutralMode(NeutralMode.Coast);
        leftBackMotor.setNeutralMode(NeutralMode.Coast);
        rightFrontMotor.setNeutralMode(NeutralMode.Coast);
        rightBackMotor.setNeutralMode(NeutralMode.Coast);
    }

}
{public void initMotionMagic(double velocity,double accelaration, double distance} {
    MM_ditance = distance*MAX_TICKS_PER_FOOT;

    leftFrontMotor.configSelectfeedbacksensor(Feedbackdevice.QuadEncoder, MM_PIDINDEX,TIMEOUT_MS);
    rightFrontMotor.configSelectfeedbacksensor(Feedbackdevice.QuadEncoder, MM_PIDINDEX,TIMEOUT_MS);

    leftfrontmotor.configSelectfeedbacksensor(Feedbackdevice.QuadEncoder,MM_PIDINDEX,TIMEOUT_MS)
    rightfrontmotor.configSelectfeedbacksensor(Feedbackdevice.QuadEncoder,MM_PIDINDEX,TIMEOUT_MS)

} {leftFrontMotor.configNominaloutputforward(0,TIMEOUT_MS);}
} {leftFrontMotor.configNominaloutputreverse(0,TIMEOUT_MS);}
} {leftFrontMotor.configNominaloutputforward(1,TIMEOUT_MS);}
} {leftFrontMotor.configNominaloutputreverse(-1,TIMEOUT_MS);}



} {rightFrontMotor.configNominaloutputforward(0,TIMEOUT_MS);}
} {rightFrontMotor.configNominaloutputreverse(0,TIMEOUT_MS);}
} {rightFrontMotor.configNominaloutputforward(1,TIMEOUT_MS);}
} {rightFrontMotor.configNominaloutputreverse(-1,TIMEOUT_MS);}

{leftfrontmotor.selectProfileSlot(MM_PIDSLOT,MM_PIDINDEX)
{rightfrontmotor.selectProfileSlot(MM_PIDSLOT,MM_PIDINDEX)]}

{leftfrontmotor.config_kP(0, MM_P, TIMEOUT_MS)}
{leftfrontmotor.config_kP(0, MM_I, TIMEOUT_MS)}
{leftfrontmotor.config_kP(0, MM_D, TIMEOUT_MS)}
{leftfrontmotor.config_kP(0, MM_F, TIMEOUT_MS)}

{rightfrontmotor.config_kP(0, MM_P, TIMEOUT_MS)}
{rightfrontmotor.config_kP(0, MM_I, TIMEOUT_MS)}
{rightfrontmotor.config_kP(0, MM_D, TIMEOUT_MS)}
{rightfrontmotor.config_kP(0, MM_F, TIMEOUT_MS)}

{leftfrontmotor.configmotionaccerlation(accelaration, TIMEOUT_MS)
    {leftfrontmotor.configmotioncruisevelocity(velocity, TIMEOUT_MS)
    
        {leftfrontmotor.setselectedsensorposition(0, MM_PIDINDEX, TIMEOUT_MS)}
        {rightfrontmotor.setselectedsensorposition(0, MM_PIDINDEX, TIMEOUT_MS)}

leftfrontmotor.ser(ControlMode.MotionMagic,MM_distance);
rightfrontmotor.set(ControlMode.Motionmagic,MM_distance);




public boolean isAtPIDDestination(){
    return (math.abs(leftFrontMotor.getselectedsensorposition())) -MM_distance < Threshold
    mathab
}





